version: '3.8'
services:
  front:
    image: px/front:local
    build:
      context: ./front/
      target: runner
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=secret
  backend:
    image: px/server:local
    build:
      context: ./server/
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=secret
